# -*- coding: utf-8 -*-
"""survival.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCC82GwzwuyYFmuXL4cItc1qiDtJUecQ
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression


surv = pd.read_csv("accident.csv")


surv.dropna(inplace=True)


surv['Gender'] = surv['Gender'].str.lower()
surv['Helmet_Used'] = surv['Helmet_Used'].str.lower()
surv['Seatbelt_Used'] = surv['Seatbelt_Used'].str.lower()

le_gender = LabelEncoder()
le_helmet = LabelEncoder()
le_seatbelt = LabelEncoder()

surv['Gender'] = le_gender.fit_transform(surv['Gender'])
surv['Helmet_Used'] = le_helmet.fit_transform(surv['Helmet_Used'])
surv['Seatbelt_Used'] = le_seatbelt.fit_transform(surv['Seatbelt_Used'])


a = surv[['Age', 'Gender', 'Speed_of_Impact', 'Helmet_Used', 'Seatbelt_Used']]
b = surv['Survived']


LR = LogisticRegression()
LR.fit(a, b)


print("Known genders:", list(le_gender.classes_))
print("Known helmet used labels:", list(le_helmet.classes_))
print("Known seatbelt used labels:", list(le_seatbelt.classes_))

age = float(input("Enter age: "))
gender = input("Enter gender: ").strip().lower()
speed_impact = float(input("Enter speed of impact: "))
helmet_used = input("Enter helmet used (yes/no): ").strip().lower()
seatbelt_used = input("Enter seatbelt used (yes/no): ").strip().lower()


if gender not in le_gender.classes_:
    print(f"Error: '{gender}' not recognized. Valid options: {list(le_gender.classes_)}")
    exit()

if helmet_used not in le_helmet.classes_:
    print(f"Error: '{helmet_used}' not recognized. Valid options: {list(le_helmet.classes_)}")
    exit()

if seatbelt_used not in le_seatbelt.classes_:
    print(f"Error: '{seatbelt_used}' not recognized. Valid options: {list(le_seatbelt.classes_)}")
    exit()


gender_encoded = le_gender.transform([gender])[0]
helmet_encoded = le_helmet.transform([helmet_used])[0]
seatbelt_encoded = le_seatbelt.transform([seatbelt_used])[0]

pred = LR.predict([[age, gender_encoded, speed_impact, helmet_encoded, seatbelt_encoded]])[0]

print("Survival:", "Yes" if pred == 1 else "No")


print("Model accuracy:", LR.score(a, b))